services:
    # add container for mongodb, rabbitmq management, redis
    db:
        image: postgres:18-alpine
        container_name: auth_postgres
        restart: always
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASS}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - 5432:5432
        volumes:
            - postgres:/var/lib/postgresql

volumes:
    postgres:
